name: Generate Docs and Deploy to GitHub Pages
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    env:
      CONFIG_FILE: docs/mkdocs.yml
      REQUIREMENTS: docs/requirements.txt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install "mkdocs>=1.6.1,<1.7.0" "mkdocs-glightbox>=0.4.0,<0.5.0" "mkdocs-material>=9.6.15,<10.0.0" "mkdocs-include-markdown-plugin>=7.1.6,<8.0.0" "mkdocs-static-i18n==1.3.0" "mkdocs-timetoread-plugin>=0.0.4,<0.1.0"
      - run: mkdocs gh-deploy --force --config-file docs/mkdocs.yml
